apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_USER: "{{ .Values.postgres.user | b64enc }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.password | b64enc }}"
  POSTGRES_DB: "{{ .Values.postgres.database | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secrets
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: "{{ .Values.pgadmin.email | b64enc }}"
  PGADMIN_DEFAULT_PASSWORD: "{{ .Values.pgadmin.password | b64enc }}"
