apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: prisma-migrate
        image: "{{ .Values.denoApi.image }}"
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Starting migration..."
            npx prisma migrate deploy --schema=./prisma/schema.prisma
            echo "Migration completed successfully"
        envFrom:
          - configMapRef:
              name: app-config
  backoffLimit: 4