kubectl apply -f kubernetes-dashboard-sa.yaml &&
kubectl apply -f kubernetes-dashboard-crb.yaml &&
kubectl apply -f metrics-server.yaml &&
kubectl apply -f k8s-sc.yaml &&
kubectl apply -f k8s-pvcs.yaml &&
kubectl apply -f k8s-secrets.yaml &&
kubectl apply -f k8s-config.yaml &&
kubectl apply -f k8s-postgres.yaml &&
kubectl apply -f k8s-pgadmin.yaml &&
kubectl apply -f k8s-deno-api.yaml &&
