apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=  # admin (base64 encoded)
  POSTGRES_PASSWORD: YWRtaW5wYXNzd29yZA==  # adminpassword (base64 encoded)
  POSTGRES_DB: cG9zdGdyZXNfZGI=  # postgres_db (base64 encoded)
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secrets
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AYWRtaW4uY29t  # admin@admin.com (base64 encoded)
  PGADMIN_DEFAULT_PASSWORD: YWRtaW4=  # admin (base64 encoded)
