# deno-api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deno-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deno-api
  template:
    metadata:
      labels:
        app: deno-api
    spec:
      containers:
        - name: deno-api
          image: k8-test-deno-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: deno-api-service
spec:
  selector:
    app: deno-api
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
